name = "notification-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "notifforwader.rifki.my.id", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "notifications-db"
database_id = "69b76196-1bda-4377-a65e-49d0987f82fe"

[[kv_namespaces]]
binding = "CONFIG"
id = "dc9b98a383064471be6cb70cfaf56a52"

[vars]
ENVIRONMENT = "production"
